export const ADD_TO_CART ='ADD_TO_CART';
export const REMOVE_ONE_FROM_CART ='REMOVE_ONE_FROM_CART';
export const REMOVE_ALL_FROM_CART ='REMOVE_ALL_FROM_CART';
export const CLEAR_CART ='CLEAR_CART'

export const ADD_TO_FAV ='ADD_TO_FAV';
export const REMOVE_ONE_FROM_FAV ='REMOVE_ONE_FROM_FAV';
export const REMOVE_ALL_FROM_FAV ='REMOVE_ALL_FROM_FAV';
export const CLEAR_FAV ='CLEAR_FAV'